# Jekyll Resume Theme

# Site settings
title: MICCA Report
email: displaylab@umich.edu
description: Michigan Collaborative for Contraceptive Access
baseurl: ""
url: "https://www.contraceptiveaccess.org/"
name: MICCA Performance Reporting Tool
languages: HTML, CSS and Javascript
email_address: displaylab@umich.edu
codepen_username: false
github_username: false
twitter_username: false

# Build settings
markdown: kramdown

exclude:
  - README.md
  - stack.yml

defaults:
  - scope:
      path: "assets/pdf/measures"
    values:
      measure: true
