# Navivation
# dashboard and submit endpoints are local only stubs
nav_items:
  - title: Validate data
    path: /validate.html
  - title: Dashboard
    path: /dashboard
  - title: Submit data
    path: /submit
